services:
  ecommerce-api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    container_name: ecommerce-api

    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile

    networks:
      - app-network

    ports:
      - "5000:5000"
      - "5002:5002"

networks:
  app-network:
    external: true
    name: ecommerce-network