services:

  database-postgres:
    image: postgres:18
    container_name: database-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/18/docker

    ports:
      - "5432:5432"

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - ecommerce-network

  cache-redis:
    image: redis:8

    container_name: cache-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - ecommerce-network

volumes:
  postgres-data:

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge