events {}

http {

    upstream ecommerce_api {
        server ecommerce-api:8080;
    }

    server {

        listen 80;
        server_name api.example.com;

        return 301 https://$host$request_uri;
    }

    server {

        listen 443 ssl;
        http2 on;

        server_name api.example.com;

        ssl_certificate     /etc/letsencrypt/live/api.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.example.com/privkey.pem;

        location / {

            proxy_pass http://ecommerce_api;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}